### ISSUE TITLE
Date filtering for `AgendaItem` too strict.

### ISSUE THREAD

**Issue by barend** [sebastiaanschool/sebastiaanschool-backend#2]
https://github.com/sebastiaanschool/sebastiaanschool-backend/blob/52c63283f937ee66e07d3979e72b18a7d2aa8be2/backend/views.py#L19-L20

This date filtering rule seems too strict. 
1. If an event started last week and ends tomorrow, it won't be in the result set. This seems like fully a bug to me.
2. Generally speaking, I may want to see events two weeks or a month back in time, perhaps to jog my memory what date something happened. This seems like an enhancement, but I'm not sure it solves a problem anyone has.

**Comment by jeroenleenarts** [comment]
Requested input from domain expert.

**Comment by jeroenleenarts** [comment]
> 1. Als er iets plaats vindt vandaag en morgen eindigt ( zoals vakanties schoolkamp) komt dat niet goed in de agenda te staan begrijp ik. Dat is wel vervelend. We hebben natuurlijk veel gebeurtenissen die  maar plaats vinden op 1 dag, Maar juist de vakanties bevatten natuurlijk meerdere dagen.
> 2. Ik vind het ook wel fijn om terug te kunnen kijken welke activiteiten er geweest zijn, maar ik weet niet of dit voor ouders erg belangrijk is.

**Comment by jeroenleenarts** [comment]
Seems clear to me. Always show items that are still ongoing. And have a toggle available to switch between [current+future items / all items ].
